create database PIZZERIA;
use PIZZERIA;


CREATE TABLE `COMANDA` (
  ID int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATA datetime NOT NULL,
  NOM varchar(100) NOT NULL,
  LLINATGES varchar(100) NOT NULL,
  DNI varchar(9) NOT NULL,
  EMAIL varchar(100) NOT NULL,
  PIZZA varchar(3) NOT NULL COMMENT 'MAR=Margarita,EST=4 Estacions, NAP=Napolitana, QUE=4 formatges',
  MIDA enum('M','L','XL','XXL') NOT NULL,
  PREU float NOT NULL DEFAULT '0'
);


CREATE TABLE `INGREDIENT` (
  CODI varchar(5) NOT NULL PRIMARY KEY,
  NOM varchar(100) NOT NULL
);


CREATE TABLE `INGREDIENTS_COMANDA` (
  ID_COMANDA int(100) NOT NULL,
  CODI_INGREDIENT varchar(5) NOT NULL,
  PRIMARY KEY (ID_COMANDA, CODI_INGREDIENT),
  FOREIGN KEY (ID_COMANDA) REFERENCES COMANDA(ID) ON DELETE CASCADE,
  FOREIGN KEY (CODI_INGREDIENT) REFERENCES INGREDIENT(CODI)
);


